site_name: Lamontagne Lab at Tufts University
site_url: https://mydomain.org/mysite

repo_name: LamontagneLab/lab-manual
repo_url: https://github.com/LamontagneLab/lab-manual

theme:
  name: material
  palette:
    primary: blue